apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: pwjap9u37-python 
  janus-idp.io/tekton: pwjap9u37-python
  backstage.io/kubernetes-id: pwjap9u37-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: pwjap9u37-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml