apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: pwjap9u37-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:2c86af244c0bb8cd33f355f77371a9fbbb1d9ba4@sha256:390d0f14afde6fa7fa33257e379d359fd25934fb060f8e0765cc4b87683a7cc1
          name: container-image
